FROM rustlang/rust:nightly-slim
LABEL maintainer="Michael van Niekerk <mvniekerk@gmail.com>"

RUN cargo --version
RUN apt-get update; apt install -y libgtk-3-dev

RUN mkdir /project
WORKDIR /project
CMD /bin/bash
